name: Update Job


    
on: workflow_dispatch


jobs:
  run_daily_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.18
        
      - name: Add and Commit File
        run: |
          git config --local user.email "xznwwh@gmail.com"
          git config --local user.name "xznwwh"

 
      - name: Run Python Script
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python vls.py
          
      - name: Check for Changes
        run: |
          git status
          git add myips.csv
          git diff --cached --exit-code || git commit -m "update"

          
      - name: Push Changes
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         
